#ifndef __MOTORDRIVER_MOTOR_DRIVER_CONFIG_H__
#define __MOTORDRIVER_MOTOR_DRIVER_CONFIG_H__

#include "driver/gpio.h"
#include "driver/pwm.h"

#include <stdint.h>

#define MOTOR_DRIVER_PWM_TYPE uint8_t
#define MOTOR_DRIVER_GPIO_TYPE gpio_num_t

#define MOTOR_DRIVER_SET_GPIO_STATE(pGPIO, state) gpio_set_level(*(pGPIO), (state))

#define MOTOR_DRIVER_LEFT_FORWARD_PIN GPIO_NUM_2
#define MOTOR_DRIVER_LEFT_BACKWARD_PIN GPIO_NUM_4
#define MOTOR_DRIVER_LEFT_PWM_PIN GPIO_NUM_5
#define MOTOR_DRIVER_LEFT_PWM_CHANNEL 0

#define MOTOR_DRIVER_RIGHT_FORWARD_PIN GPIO_NUM_12
#define MOTOR_DRIVER_RIGHT_BACKWARD_PIN GPIO_NUM_13
#define MOTOR_DRIVER_RIGHT_PWM_PIN GPIO_NUM_15
#define MOTOR_DRIVER_RIGHT_PWM_CHANNEL 1

#define MOTOR_DRIVER_STBY_PIN GPIO_NUM_14

#define MOTOR_DRIVER_PWM_PERIOD 30

#endif // __MOTORDRIVER_MOTOR_DRIVER_CONFIG_H__
